CREATE UNIQUE NONCLUSTERED INDEX IX_Roles_Name ON dbo.Roles
	(
	Name
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

UPDATE [Settings] SET [Value]='2017-09-23 03:25:00' WHERE [Name]='database.version'